FROM mongo:3.6
LABEL maintainer="stevenbetancurt@hotmail.com"

VOLUME [ "/backup" ]

# docker build -t stevensotelo/aclimate_db:latest .

# docker run --name aclimate_db -p 27017:27017 --env-file ./.env -v D:/CIAT/Code/USAID/usaid_forecast_docker/database/backup:/backup -d stevensotelo/aclimate_db:latest

# docker exec -it aclimate_db bash
# docker logs aclimate_db